# Generated by Django 2.0.4 on 2018-04-19 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('upload_size', models.FloatField()),
            ],
        ),
    ]
