# Generated by Django 2.0.4 on 2018-04-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupmodel',
            name='upload_path',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
