# Generated by Django 2.0.4 on 2018-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180420_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupmodel',
            name='upload_group',
            field=models.CharField(default='', max_length=50),
        ),
    ]
